# Generated by Django 3.2.9 on 2021-11-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_comment_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rank',
            field=models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], default='★★★★★', max_length=50),
        ),
    ]
